env: standard
runtime: nodejs10
service: hti-web-fe

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|eot|svg|ttf|woff|png|jpeg|jpg|gif))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|eot|svg|ttf|woff|png|jpeg|jpg|gif)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
